Header
JollyGolf/Landing pull request #2
Opened 2017-07-08 12:50 UTC by JollyGolf

2017-07-08 14:04 UTC, ShepelievD requested changes

2017-07-08 14:04 UTC, ShepelievD commented on branch/header/header.html
> +	<a href="#">HOME</a>&nbsp&nbsp&nbsp
а точку с запятой в конце `&nbsp`?

2017-07-08 14:04 UTC, ShepelievD commented on branch/header/header.html
> +</div>
энтер в конце каждого файла, чтобы гит понимал где заканчивается

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> +	font-family: BrockScript;
перед `{` пробел + выравнивание

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> +	font-family: DaysSansBlack;
делай отступ 2 пробела

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> +	}
выравнивание, должно быть так:
```
#header {
  asd: 12px;
}
```

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> +#colfont{
айди не катит, его тяжело перебить, и непонятное название цвета, назови как-то лучше `light-blue` или что-нибуь такое

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> +a{text-decoration: none;
выравнивание

2017-07-08 14:04 UTC, ShepelievD commented on index.css
> + }
энтер

2017-07-08 14:04 UTC, ShepelievD commented on branch/header/header.html
> +<div id="header">
убери везде id и поставь class

2017-07-08 14:04 UTC, ShepelievD commented on branch/header/header.html
> +<nav id="main_nav">
выравнивание непонятно, должно быть так:
```
<div>
  <span>TEXT</span>
</div>
```

2017-07-10 19:21 UTC, ShepelievD requested changes

2017-07-10 19:21 UTC, ShepelievD commented on branch/header/header.html
> +    <nav class="main_nav">
через дефис

2017-07-10 19:21 UTC, ShepelievD commented on index.css
> +}
энтер

2017-07-10 19:21 UTC, ShepelievD commented on index.css
> +.header {
всё что касается header - в header.css и так далее

2017-07-10 19:21 UTC, ShepelievD commented on index.css
> +  margin-left:  -8px;
лишние пробелы, что за ширина странная такая

2017-07-10 20:07 UTC, JollyGolf commented on branch/header/header.html
> +    <nav class="main_nav">
что именно через дефис?

2017-07-10 20:18 UTC, ShepelievD commented on branch/header/header.html
> +    <nav class="main_nav">
название, `main-nav`

2017-07-10 20:24 UTC, JollyGolf commented on index.css
> +  margin-left:  -8px;
width: 100%; ?

2017-07-10 20:26 UTC, ShepelievD commented on index.css
> +  margin-left:  -8px;
если это див, то у него и так будет ширина 100%

2017-07-11 06:15 UTC, ShepelievD approved these changes

2017-07-11 06:16 UTC, merged